package permission

// Read-only lines (danger level 只读): default mode runs them unasked under
// Git Bash and PowerShell; under the cmd.exe fallback they ask (ro()).
// Sources: classifier_test.go (TestClassifyLineReadOnly), lookup_readonly_test.go,
// classifier_unc_test.go, classifier_pkg_test.go, classifier_git_branch_test.go,
// manual 权限模式 "只读命令如何判定".

// gitListing is a git listing command (branch/tag/stash list): read-only,
// though its subcommand belongs to the git group. An ask or deny rule on the
// git group covers only the group's non-read-only usages (manual), so
// ask-git-group leaves it unasked (it used to ask); under cmd.exe, where
// nothing is read-only, [a]/[p] remembers the group, which covers it.
func gitListing(cmd, note string) []permCase {
	return ro(cmd, note, cmdRem(rememberGroup))
}

var corpusReadOnly = join(
	// git read-only subcommands
	ro("git status", "只读 git 子命令免询问", cmdDecides(scParamMatch, DAllow)),
	ro("git status -s", "只读 git 子命令带短选项", cmdDecides(scParamMatch, DAllow)),
	ro("git status --short --branch", "只读 git 子命令带长选项", cmdDecides(scParamMatch, DAllow)),
	ro("git diff", "git diff 只读"),
	ro("git diff --stat", "git diff 选项不改变只读"),
	ro("git diff --cached", "git diff --cached 只读"),
	ro("git diff HEAD~1 -- main.go", "git diff 带 -- 路径"),
	ro("git log --oneline", "git log 只读"),
	ro("git log --oneline -5", "手册示例 git log --oneline -5"),
	ro("git --no-pager log -3", "--no-pager 全局选项不破坏只读", cmdRem(rememberNone)),
	ro("git -C sub status", "-C dir 全局选项不破坏只读", cmdRem(rememberNone)),
	ro("git show HEAD", "git show 只读"),
	ro("git show --stat HEAD", "git show --stat 只读"),
	ro("git blame main.go", "git blame 只读"),
	ro("git ls-files", "git ls-files 只读"),
	ro("git rev-parse HEAD", "git rev-parse 只读"),
	ro("git rev-parse --show-toplevel", "git rev-parse --show-toplevel 只读"),
	ro("git --version", "工具探测 git --version 只读", cmdRem(rememberNone)),
	ro("git remote -v", "git remote -v 列表只读"),
	ro("git log 2>/dev/null", "重定向到 /dev/null 不算写文件"),
	gitListing("git branch", "git branch 无参数只列出"),
	gitListing("git branch -a", "git branch -a 列表选项"),
	gitListing("git branch -avv", "组合列表短选项"),
	gitListing("git branch -r", "git branch -r"),
	gitListing("git branch --show-current", "git branch --show-current"),
	gitListing("git branch --merged main", "--merged 取值是列表过滤"),
	gitListing("git branch --no-merged", "--no-merged 列表"),
	gitListing("git branch --contains HEAD", "--contains 取值是列表过滤"),
	gitListing("git branch --points-at HEAD", "--points-at 列表"),
	gitListing("git branch --color=always -a", "--color= 带值列表选项"),
	gitListing("git branch -q --list", "-q --list"),
	gitListing("git branch -l feat/x", "-l 带模式是列表"),
	gitListing("git tag", "git tag 无参数只列出"),
	gitListing("git stash list", "git stash list 只读"),

	// file inspection
	ro("ls", "ls 只读"),
	ro("ls -la", "手册示例 ls -la"),
	ro("ls /usr", "绝对路径参数不影响只读（非 UNC）"),
	ro("dir", "dir 只读"),
	ro("pwd", "pwd 只读"),
	ro("cat go.mod", "手册示例 cat go.mod"),
	ro("cat ./x", "相对路径参数"),
	ro("cat a/b", "带斜杠路径参数（非 UNC）"),
	ro("head -n 20 main.go", "head 只读"),
	ro("tail -n 50 build.log", "tail 只读"),
	ro("wc -l main.go", "wc 只读"),
	ro("du -sh .", "du 只读"),
	ro("df -h", "df 只读"),
	ro("stat main.go", "stat 只读"),
	ro("realpath .", "realpath 只读"),
	ro("basename a/b.go", "basename 只读"),
	ro("dirname a/b.go", "dirname 只读"),
	ro("file main.go", "file 无 -C 只读"),
	ro("tree", "tree 无输出选项只读"),
	ro("tree -L 2", "tree -L 不写文件"),

	// search
	ro("grep -rn foo .", "手册示例 grep -rn foo ."),
	ro(`grep -n "// TODO" main.go`, "// 后跟空格不是 UNC 主机名"),
	ro("egrep -i err build.log", "egrep 只读"),
	ro("fgrep -x main go.mod", "fgrep 只读"),
	ro(`find . -name "*.go"`, "find 无动作选项只读"),
	ro("find . -type f -newer go.mod", "find 过滤选项只读"),
	ro("rg foo", "rg 只读"),
	ro("rg -n --hidden foo src", "rg 常规选项只读"),
	ro("ag foo", "ag 无 --pager 只读"),
	ro("locate main.go", "locate 只读"),

	// system information
	ro("printenv", "printenv 只读"),
	ro("which gh", "工具探测 which"),
	ro("whoami", "whoami 只读"),
	ro("uname -a", "uname 只读"),
	ro("uptime", "uptime 只读"),
	ro("id", "id 只读"),
	ro("groups", "groups 只读"),
	ro("hostname", "hostname 无参数只读"),
	ro("date", "date 无参数只读"),
	ro("date -u", "date -u 不设时钟"),
	ro("date +%Y-%m-%d", "date +FORMAT 只读"),
	ro("date -u +%s", "date -u +FORMAT"),
	ro("date --utc", "date --utc 长选项"),
	ro("date -R", "date -R"),
	ro("date --iso-8601=seconds", "date --iso-8601= 带值"),
	ro("date -d yesterday", "date -d 取值是日期不是设时钟"),
	ro("command -v gh", "command -v 只查找名字", cmdRem(rememberNone)),
	ro("command -V gh", "command -V 只查找名字", cmdRem(rememberNone)),
	ro("true", "true 只读"),
	ro("echo hi", "echo 只读"),
	ro("echo 'keyboard word'", "含 dd 字母的参数不误判"),

	// directory changes and read-only chains
	ro("cd proj && git status", "手册：cd 本身只读，整行只读"),
	ro("cd src && ls", "cd && ls 整行只读"),
	ro("cd proj && git remote -v", "手册示例 cd proj && git remote -v"),
	ro("pushd src && ls && popd", "pushd/popd 只读"),
	ro("git status && git diff", "手册示例 链式只读"),
	ro("git status && git diff | grep x", "链式 + 管道只读"),
	ro("git log --oneline -5 | head -3", "管道到只读命令"),
	ro("cat file.go | wc -l", "管道两端只读"),
	ro("git status; echo ok", "分号链只读"),
	ro("ls; pwd", "分号链只读"),
	ro("git log || true", "|| 链只读"),
	ro("which gh\ngit --version", "换行分隔的两条只读命令", cmdRem(rememberNone)),
	ro("ls 2>/dev/null", "stderr 丢弃不是写文件"),
	ro("git status > /dev/null", "stdout 丢弃不是写文件", cmdDecides(scParamMatch, DAllow)),

	// build tools' read-only subcommands
	ro("go env GOPATH", "go env 读取只读"),
	ro("npm list", "npm list 只读", cmdRem(rememberGroup)),
	ro("npm view react", "npm 内置 view 只读"),
	ro("npm explain react", "npm 内置 explain 只读"),
	ro("npm doctor", "npm doctor 是内置命令（非脚本）"),
	ro("npm audit", "npm audit 无 fix 只读", cmdRem(rememberGroup)),
	ro("npm audit --json", "npm audit --json", cmdRem(rememberGroup)),
	ro("pnpm why react", "pnpm 内置 why 只读"),
	ro("pnpm view react", "pnpm 内置 view"),
	ro("pnpm outdated", "pnpm outdated", cmdRem(rememberGroup)),
	ro("pnpm audit", "pnpm audit 无 --fix", cmdRem(rememberGroup)),
	ro("composer show", "composer 内置 show"),
	ro("composer info x", "composer 内置 info"),
	ro("composer outdated", "composer outdated"),
	ro("composer why x", "composer why"),
	ro("composer search x", "composer search"),
	ro("pip freeze", "pip freeze 只读"),
	ro("pip show requests", "pip show 只读"),
	ro("brew doctor", "brew doctor 只读"),
	ro("gem list", "gem list 只读"),
	ro("docker ps", "docker ps 只读"),

	// PowerShell cmdlets (also plain words under bash)
	ro("Get-ChildItem", "PowerShell Get-ChildItem 只读"),
	ro("gci -Recurse", "Get-ChildItem 别名"),
	ro("Get-Content README.md", "Get-Content 只读"),
	ro("Get-Location", "Get-Location 只读"),
	ro("Test-Path go.mod", "Test-Path 只读"),
	ro("Get-Item go.mod", "Get-Item 只读"),
	ro("Resolve-Path .", "Resolve-Path 只读"),
	ro("Get-Command git", "Get-Command 只读"),
	ro("Set-Location src", "Set-Location 只读（手册）"),
)
